numpy matplot이 끝나면 필기시험 - 코드를 주면 결과를 적는 시험을 볼 예정!! 

## numpy 모듈

In [1]:
import numpy as np

In [2]:
arr = [1,2,3]
print(type(arr))

<class 'list'>


In [4]:
arr1 = np.array([1,2,3]) #int arr1[3] = {1,2,3};
print(type(arr1), arr1)

<class 'numpy.ndarray'> [1 2 3]


In [9]:
arr2 = np.array(5) #int arr2 = 5;
print(type(arr2), arr2, arr2.shape) #스칼라값

<class 'numpy.ndarray'> 5 ()


In [6]:
print(arr1.shape, arr2.shape) #arr1-1차원 배열인데 값이 3

(3,) ()


In [8]:
arr3= np.array([[1,2,3],[10,20,30]])  #int arr3[2][3] = {{1,2,3},{10,20,30}};
print(arr3, type(arr3), arr3.shape) #2x3

[[ 1  2  3]
 [10 20 30]] <class 'numpy.ndarray'> (2, 3)


In [10]:
arr3[1,1], arr3[1][1] #arr3[1][1]

(20, 20)

In [11]:
arr3[0,1], arr3[0][1] #arr3[0][1]

(2, 2)

In [12]:
print(arr1)

[1 2 3]


In [13]:
arr4 = np.array([arr1, arr1, arr1, arr1]) #[[1,2,3],[],[],[]] -> arr4[4][3]
print(arr4, arr4.shape)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]] (4, 3)


In [14]:
print(arr3, arr3.shape)

[[ 1  2  3]
 [10 20 30]] (2, 3)


In [15]:
arr5 = np.array([arr3, arr3]) #[[[1,2,3],[10,20,30]],[[1,2,3],[10,20,30]]]
                              #int arr5[2][2][3] *3차원 중요*
print(arr5, arr5.shape)

[[[ 1  2  3]
  [10 20 30]]

 [[ 1  2  3]
  [10 20 30]]] (2, 2, 3)


In [16]:
arr = np.array([[1],[1],[1]]) #int arr[3][1]
print(arr, arr.shape)

[[1]
 [1]
 [1]] (3, 1)


In [17]:
arr = np.array([[[1]]]) #int arr[1][1][1]
print(arr, arr.shape)

[[[1]]] (1, 1, 1)


(512,512,3)->이미지

### 연습문제1

In [64]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])
arr3 = np.array([4,5,6])
print(arr1, arr1.shape, arr2, arr2.shape, arr3, arr3.shape)

[1 2 3] (3,) [10 20 30] (3,) [4 5 6] (3,)


In [65]:
arr4= np.array([arr1, arr2, arr3])
print(arr4, arr4.shape)

[[ 1  2  3]
 [10 20 30]
 [ 4  5  6]] (3, 3)


## zeros, ones

In [18]:
arr = np.zeros([3,4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
arr_ones = np.ones([3,4])
arr_ones, arr_ones.shape

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 (3, 4))

In [20]:
onesx5 = np.ones([4,3])*5
onesx5 

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [21]:
onesx5 = 5* np.ones([4,3])
onesx5 

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

### 연습문제2

In [79]:
arr1 = np.ones([3,3])
arr2 = (arr1 + 1) + arr1
arr2

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [94]:
import numpy as np
arr2= np.ones([5,5])
arr2[1:-1,1:-1]=0
print(arr2)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## arange 함수

In [23]:
abc = list(range(0,10,2))  #list를 붙이지 않으면 range함수임
print(abc)

[0, 2, 4, 6, 8]


In [25]:
arr = np.arange(5)
arr, arr.shape

(array([0, 1, 2, 3, 4]), (5,))

In [26]:
arr1 = np.arange(4,9)
arr1, arr1.shape

(array([4, 5, 6, 7, 8]), (5,))

In [28]:
arr2 = np.arange(4,9,3)
arr2, arr2.shape

(array([4, 7]), (2,))

In [29]:
arr = np.arange(12) #int arr[12]={0,1,2, ... ,11}
arr, arr.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [30]:
arr3 = arr.reshape(4,3) #int arr[4][3]={{1,0,2},{},{},{9,10,11}}
arr3, arr3.shape

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 (4, 3))

In [31]:
arr1 = arr3.reshape(12)
arr1, arr1.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [32]:
arr = np.arange(12) #int arr[2][2][3]={{{0,1,2},{}},{{},{9,10,11}}}
arr3 = arr.reshape(2,2,3)
arr3, arr3.shape

(array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]]]),
 (2, 2, 3))

In [33]:
arr3.reshape(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
arr3.reshape(-1) #-1 :자동으로 계산해줌

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
arr3.reshape(3,-1) 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### 연습문제3

In [74]:
arr = np.arange(20)
odd= (arr%2==1)
print(arr[odd])

[ 1  3  5  7  9 11 13 15 17 19]


In [75]:
arr2= arr[odd].reshape(-1,5)
arr2, arr2.shape

(array([[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]]),
 (2, 5))

## indexing, slicing

In [39]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [40]:
arr[0][1][2]

5

In [41]:
arr[0,1,2]

5

In [42]:
arr[1:]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [43]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
arr[1][2]

5

In [45]:
arr[1,2]

5

In [46]:
arr[1:]

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [47]:
arr[2:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [48]:
arr[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
arr[2:,1:] #slicing

array([[ 7,  8],
       [10, 11]])

In [50]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [51]:
arr[1:3, 2:4] #for(i=1;i<3;i++) for(j=2;j<4;j++)

array([[ 7,  8],
       [12, 13]])

In [52]:
arr[:,2:4]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18]])

### 연습문제4

In [122]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [123]:
arr = arr[:,2:4]+5
arr

array([[ 7,  8],
       [12, 13]])

## boolean indexing

In [85]:
data = np.random.randn()
print(data, type(data))

-1.7439076660500572 <class 'float'>


In [87]:
data = np.random.randn(3,4) #float data[3][4], 난수를 정규분포로 
print(data, data.shape)

[[-0.24975711  0.33356933  0.34933455  1.4519999 ]
 [ 0.19317273  1.28559892 -0.11495175 -0.90621726]
 [ 1.14505233  1.06403992  3.71790905  0.22364559]] (3, 4)


In [88]:
data < 0.0

array([[ True, False, False, False],
       [False, False,  True,  True],
       [False, False, False, False]])

In [89]:
data[data < 0.0] = 0.0
print(data)

[[0.         0.33356933 0.34933455 1.4519999 ]
 [0.19317273 1.28559892 0.         0.        ]
 [1.14505233 1.06403992 3.71790905 0.22364559]]


## broadcasting

In [96]:
data + 3

array([[3.        , 3.33356933, 3.34933455, 4.4519999 ],
       [3.19317273, 4.28559892, 3.        , 3.        ],
       [4.14505233, 4.06403992, 6.71790905, 3.22364559]])

In [97]:
data

array([[0.        , 0.33356933, 0.34933455, 1.4519999 ],
       [0.19317273, 1.28559892, 0.        , 0.        ],
       [1.14505233, 1.06403992, 3.71790905, 0.22364559]])

In [98]:
print(data*5)

[[ 0.          1.66784667  1.74667273  7.25999948]
 [ 0.96586367  6.42799459  0.          0.        ]
 [ 5.72526164  5.32019959 18.58954524  1.11822796]]


In [99]:
data + np.array([1,2,3,4])

array([[1.        , 2.33356933, 3.34933455, 5.4519999 ],
       [1.19317273, 3.28559892, 3.        , 4.        ],
       [2.14505233, 3.06403992, 6.71790905, 4.22364559]])

In [101]:
arr = np.random.randint(7,size=27)
arr

array([3, 2, 6, 3, 1, 6, 3, 0, 1, 1, 3, 6, 6, 0, 1, 4, 5, 4, 0, 5, 5, 4,
       4, 1, 5, 1, 5])

In [105]:
arr = np.random.randint(2,size=27).reshape(3,3,3) #int arr[3][3][3]
arr2= np.random.randint(2,size=9).reshape(3,3)
arr, arr2

(array([[[1, 0, 1],
         [1, 0, 1],
         [1, 0, 0]],
 
        [[1, 1, 1],
         [1, 0, 1],
         [0, 0, 0]],
 
        [[0, 0, 1],
         [1, 1, 1],
         [1, 0, 0]]]),
 array([[0, 0, 1],
        [1, 0, 0],
        [0, 1, 1]]))

In [106]:
arr + arr2 

array([[[1, 0, 2],
        [2, 0, 1],
        [1, 1, 1]],

       [[1, 1, 2],
        [2, 0, 1],
        [0, 1, 1]],

       [[0, 0, 2],
        [2, 1, 1],
        [1, 1, 1]]])

In [107]:
arr

array([[[1, 0, 1],
        [1, 0, 1],
        [1, 0, 0]],

       [[1, 1, 1],
        [1, 0, 1],
        [0, 0, 0]],

       [[0, 0, 1],
        [1, 1, 1],
        [1, 0, 0]]])

### 연습문제6

In [130]:
arr = np.random.randint(2,size=16).reshape(2,2,2,2)
arr2= np.random.randint(2,size=4).reshape(2,2) #size가 같아야함
print(arr)
print(arr2)
arr+arr2

[[[[0 1]
   [0 0]]

  [[1 0]
   [1 0]]]


 [[[1 1]
   [1 0]]

  [[1 1]
   [0 0]]]]
[[1 0]
 [0 1]]


array([[[[1, 1],
         [0, 1]],

        [[2, 0],
         [1, 1]]],


       [[[2, 1],
         [1, 1]],

        [[2, 1],
         [0, 1]]]])

## 수학연산 함수

In [108]:
arr

array([[[1, 0, 1],
        [1, 0, 1],
        [1, 0, 0]],

       [[1, 1, 1],
        [1, 0, 1],
        [0, 0, 0]],

       [[0, 0, 1],
        [1, 1, 1],
        [1, 0, 0]]])

In [109]:
np.sum(arr), np.max(arr)

(15, 1)

In [110]:
arr = np.random.randn(3,4)
arr

array([[-1.38455078e+00,  1.74378622e+00,  6.51763485e-01,
         1.52243961e+00],
       [ 2.24968069e+00,  3.37557048e-01, -1.65792590e+00,
         5.40374987e-04],
       [ 9.80758487e-02, -1.55442325e+00, -6.46581849e-01,
        -2.30522841e-01]])

In [111]:
np.sum(arr), np.max(arr), np.min(arr), np.mean(arr)

(1.1298386552058415,
 2.249680688616957,
 -1.6579258993369923,
 0.09415322126715346)

$ arg max_i f(i) $

arg = argument

In [112]:
arr1 = np.array([1,6,3,7,9,0])
arr1

array([1, 6, 3, 7, 9, 0])

In [113]:
np.argmax(arr1) #9가 젤큼 9는 4번째 인덱스

4

In [114]:
np.argmin(arr1)

5

In [115]:
arr = np.array([1,1,1,3,5,6,6])
arr

array([1, 1, 1, 3, 5, 6, 6])

In [116]:
np.unique(arr) #중복제거 (합집합과 유사)

array([1, 3, 5, 6])

### 연습문제6

In [120]:
arr = np.array([1,1,1,3,5,6,6])
np.argmax(arr), np.argmin(arr)

(5, 0)

## dtype, astype

In [131]:
arr = np.array([1.,2,3]) #하나만 float해도 나머지~

In [132]:
arr

array([1., 2., 3.])

In [133]:
arr.dtype

dtype('float64')

In [134]:
arr = arr.astype('int8')
arr.dtype

dtype('int8')

In [135]:
arr = arr.astype('float32')
arr.dtype

dtype('float32')

In [138]:
np.float(arr[1])

2.0

In [140]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [141]:
arr = arr.reshape(5,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [142]:
arr = arr.reshape(2,-1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [143]:
arr = arr.reshape(1,-1)
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [144]:
arr = arr.reshape(-1,1)
arr

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### 연습문제7

In [161]:
arr = np.array([1.,2,3])
arr.dtype

dtype('float64')

In [162]:
arr = arr.astype('unicode') #str형
arr.dtype

dtype('<U32')

## 차원 추가하기: expand_dims 
##### 학습시킬때 중요함

In [148]:
arr = arr.reshape(-1) #int arr[10]={}
print(arr, arr.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)


In [149]:
arr = np.expand_dims(arr,0) #int arr[1][10]={{1,2, ... ,9}}
print(arr, arr.shape)

[[0 1 2 3 4 5 6 7 8 9]] (1, 10)


In [150]:
arr = arr.reshape(-1) #int arr[10]={}
print(arr, arr.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)


In [151]:
arr = np.expand_dims(arr,-1) #int arr[10][1]={{0},{1}, ... ,{9}}
print(arr, arr.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] (10, 1)


In [152]:
arr_list = [1,2,3]
arr_list[-1] #가장 마지막

3

In [153]:
arr3 = np.arange(12).reshape(2,3,2) #int arr3[2][3][2]
arr3, arr3.shape

(array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],
 
        [[ 6,  7],
         [ 8,  9],
         [10, 11]]]),
 (2, 3, 2))

In [154]:
arr3_1 =np.expand_dims(arr3,0) #int arr3[1][2][3][2] : 0번째에 추가
arr3_1.shape

(1, 2, 3, 2)

In [155]:
arr3_2 =np.expand_dims(arr3,1) #int arr3[2][1][3][2] :1번째에 추가
arr3_2.shape

(2, 1, 3, 2)

In [156]:
arr3_4 =np.expand_dims(arr3,-1) #int arr3[2][3][2][1] :4번째에 추가
arr3_4.shape

(2, 3, 2, 1)

In [158]:
arr3_5 =np.expand_dims(np.expand_dims(arr3,-1),-1)
arr3_5.shape

(2, 3, 2, 1, 1)

### 연습문제8

In [163]:
arr3 = np.arange(12).reshape(2,3,2)
x = np.expand_dims(arr3,-1)
arr3_ =np.expand_dims(x,0)
arr3_.shape

(1, 2, 3, 2, 1)